### ISSUE TITLE
Feature suggestions - For discussion 

### ISSUE THREAD

**Issue by markojak** [odfdata/webflow-aws#21]
Firstly I want to say this is an awesome workflow. Much needed for getting a decent deployment without paying $20 for Webflow Hosting. Love it.

Some additional features I'd love to see (and will help try to contribute if you agree)

* Apply AWS tags to created resources which provides for easier management of resources in AWS
* Expand Yaml configuration for basic auth via Lamba function (https://dev.to/tastefulelk/basic-authentication-with-lambda-edge-23o5) so that you can password protect websites (or a subdomain in that website as under development) 
* Multi-site deployments by specifying which subdirectory in the root needs to be deployed to which domain
* Bump CDK v1 to v2 which is currently under maintenance only
* Perhaps can also expand functionality to support Cloudflare Workers so this can be Webflow to AWS or CloudFlare

I hope some of these are exciting. let me know what you'd like to prioritize and I can help build this out.

**Comment by fedecastelli** [comment]
hi @markojak @xavierpeich ! thanks for all the suggestions you have written. 

I'm currently working on bumping CDK version from v1 to v2 because I know it's under maintenance only. 

Once I finish, I'll prioritize the other features.

**Comment by xavierpeich** [comment]
I believe it's possible to export the CMS: https://university.webflow.com/lesson/export-collection-content. Now you might be right they are server-side rendered. What I would have in mind is importing the CMS into a DynamoDB, and mapping it somehow.

**Comment by fedecastelli** [comment]
@markojak I created different issues with what you and @xavierpeich suggested. 

I already prioritized and released a new version with the AWS CDK v2 support.

I think we should prioritize the integration of tags and than we can decide.
